
[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }
size = 12  # Ajusta el tamaño según prefieras

[general]
working_directory = "C:/Users/luisp/"
live_config_reload = true

[terminal]
osc52 = "CopyPaste"

[terminal.shell]
program = "C:/Users/luisp/AppData/Local/Microsoft/WindowsApps/Microsoft.PowerShell_8wekyb3d8bbwe/pwsh.exe" #Windows: cmd | powershell Linux: /bin/bash
args = ["-NoLogo"]

[window]
title = "Alacrity - Terminal"
dynamic_title = false
dimensions = {columns = 120, lines =30}
padding = {x=8,y=8}
decorations = "Full"
#background_opacity = 0.8
opacity = 0.9
blur = false
startup_mode = "Windowed"


[colors]

# Colores primarios
[colors.primary]
background = "#282A36"
foreground = "#EFF0EB"

# Cursor
[colors.cursor]
text = "#282A36"
cursor = "#97979B"

# Selección
[colors.selection]
text = "#EFF0EB"
background = "#3E404A"

# Colores normales
[colors.normal]
black = "#282A36"
red = "#FF5C57"
green = "#5AF78E"
yellow = "#F3F99D"
blue = "#57C7FF"
#purple = "#FF6AC1"
cyan = "#9AEDFE"
white = "#F1F1F0"

# Colores brillantes
[colors.bright]
black = "#686868"
red = "#FF5C57"
green = "#5AF78E"
yellow = "#F3F99D"
blue = "#57C7FF"
#purple = "#FF6AC1"
cyan = "#9AEDFE"
white = "#EFF0EB"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\\t" 
save_to_clipboard = false